import { useEffect, useRef } from 'react'
import type { JSX } from 'react'
import { GitBranch, Sparkles } from 'lucide-react'
import {
  ArrowUpIcon,
  CheckTinyIcon,
  ChevDownIcon,
  COMMIT_MSG,
  CursorIcon,
  FileIcon,
  PR_BODY,
  PR_TITLE,
  SHIP_FILES
} from './review-animated-visual-shared'
import { ReviewShipVisualStyles } from './review-animated-visual-ship-styles'
import { translate } from '@/i18n/i18n'

// Why: paired with ReviewNotesAnimatedVisual — same imperative pattern, but
// targets the Source Control commit-message box and the Create PR dialog so
// the user sees commit + PR generated by AI back-to-back.
export function ReviewShipAnimatedVisual(props: { reducedMotion: boolean }): JSX.Element {
  const { reducedMotion } = props
  const rootRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    if (reducedMotion) {
      return
    }
    const root = rootRef.current
    if (!root) {
      return
    }

    const cursorMaybe = root.querySelector<HTMLDivElement>('[data-cursor]')
    const sparkleMaybe = root.querySelector<HTMLButtonElement>('[data-commit-sparkle]')
    const taMaybe = root.querySelector<HTMLDivElement>('[data-commit-textarea]')
    const placeholderMaybe = root.querySelector<HTMLSpanElement>('[data-commit-placeholder]')
    const typedMaybe = root.querySelector<HTMLSpanElement>('[data-commit-typed]')
    const prGenMaybe = root.querySelector<HTMLButtonElement>('[data-pr-gen-btn]')
    const prTitleHostMaybe = root.querySelector<HTMLDivElement>('[data-pr-title]')
    const prTitleTypedMaybe = root.querySelector<HTMLSpanElement>('[data-pr-title-typed]')
    const prBodyHostMaybe = root.querySelector<HTMLDivElement>('[data-pr-body]')
    const prBodyTypedMaybe = root.querySelector<HTMLSpanElement>('[data-pr-body-typed]')
    const prCreateMaybe = root.querySelector<HTMLButtonElement>('[data-pr-create-btn]')
    if (
      !cursorMaybe ||
      !sparkleMaybe ||
      !taMaybe ||
      !placeholderMaybe ||
      !typedMaybe ||
      !prGenMaybe ||
      !prTitleHostMaybe ||
      !prTitleTypedMaybe ||
      !prBodyHostMaybe ||
      !prBodyTypedMaybe ||
      !prCreateMaybe
    ) {
      return
    }
    const rootEl: HTMLDivElement = root
    const cursor: HTMLDivElement = cursorMaybe
    const sparkle: HTMLButtonElement = sparkleMaybe
    const ta: HTMLDivElement = taMaybe
    const placeholder: HTMLSpanElement = placeholderMaybe
    const typed: HTMLSpanElement = typedMaybe
    const prGen: HTMLButtonElement = prGenMaybe
    const prTitleTyped: HTMLSpanElement = prTitleTypedMaybe
    const prBodyTyped: HTMLSpanElement = prBodyTypedMaybe
    const prCreate: HTMLButtonElement = prCreateMaybe
    const prTitlePh = prTitleHostMaybe.querySelector<HTMLSpanElement>('.ravs-placeholder')
    const prBodyPh = prBodyHostMaybe.querySelector<HTMLSpanElement>('.ravs-placeholder')
    const fileRows = Array.from(root.querySelectorAll<HTMLDivElement>('[data-sc-file]'))

    let cancelled = false
    const timers: number[] = []
    const wait = (ms: number): Promise<void> =>
      new Promise((resolve) => {
        const id = window.setTimeout(() => resolve(), ms)
        timers.push(id)
      })

    function moveCursor(anchor: HTMLElement, ox = 0, oy = 0): void {
      const pr = rootEl.getBoundingClientRect()
      const ar = anchor.getBoundingClientRect()
      cursor.style.transform = `translate(${ar.left - pr.left + ox}px, ${ar.top - pr.top + oy}px)`
    }

    function resetState(): void {
      placeholder.style.display = ''
      typed.textContent = ''
      sparkle.classList.remove('is-scanning')
      prGen.classList.remove('is-scanning')
      if (prTitlePh) {
        prTitlePh.style.display = ''
      }
      if (prBodyPh) {
        prBodyPh.style.display = ''
      }
      prTitleTyped.textContent = ''
      prBodyTyped.textContent = ''
      prCreate.classList.remove('is-flash', 'is-ready')
      const splitEl = rootEl.querySelector<HTMLDivElement>('[data-sc-split]')
      if (splitEl) {
        splitEl.classList.remove('is-ready')
      }
      fileRows.forEach((row) => row.classList.remove('is-reading'))
      cursor.classList.remove('is-visible', 'is-clicking')
      cursor.style.transition = 'none'
      cursor.style.transform = 'translate(-30px, 220px)'
      void cursor.offsetWidth
      cursor.style.transition = ''
    }

    // Why: sweeps the violet tint through the changes list once so the viewer
    // sees the AI "reading" the staged diff before any text appears — the
    // file-row pulse is the read signal (the icons themselves no longer spin).
    async function pulseFileRows(holdLastMs = 0): Promise<void> {
      for (let i = 0; i < fileRows.length; i++) {
        if (cancelled) {
          return
        }
        fileRows[i].classList.add('is-reading')
        await wait(220)
        if (i < fileRows.length - 1) {
          fileRows[i].classList.remove('is-reading')
        }
      }
      if (holdLastMs > 0) {
        await wait(holdLastMs)
      }
      fileRows.forEach((row) => row.classList.remove('is-reading'))
    }

    async function loop(): Promise<void> {
      while (!cancelled) {
        resetState()
        await wait(520)
        if (cancelled) {
          return
        }

        cursor.classList.add('is-visible')
        moveCursor(sparkle, 6, 6)
        await wait(620)
        if (cancelled) {
          return
        }

        cursor.classList.add('is-clicking')
        await wait(220)
        if (cancelled) {
          return
        }
        cursor.classList.remove('is-clicking')
        sparkle.classList.add('is-scanning')
        placeholder.style.display = 'none'
        moveCursor(ta, 200, 10)
        const scanPromise = pulseFileRows(120)
        await wait(380)
        if (cancelled) {
          return
        }

        for (const ch of COMMIT_MSG) {
          if (cancelled) {
            return
          }
          typed.textContent = (typed.textContent ?? '') + ch
          await wait(ch === '\n' ? 80 : 16)
        }
        await scanPromise
        sparkle.classList.remove('is-scanning')
        // Why: brief green flash on the Commit button signals "ready to
        // commit" without leaving a persistent tint that would compete with
        // the next beat (PR generation). Fade out before moving on.
        const splitEl = rootEl.querySelector<HTMLDivElement>('[data-sc-split]')
        if (splitEl) {
          splitEl.classList.add('is-ready')
        }
        await wait(540)
        if (splitEl) {
          splitEl.classList.remove('is-ready')
        }
        if (cancelled) {
          return
        }

        moveCursor(prGen, 11, 11)
        await wait(540)
        if (cancelled) {
          return
        }
        cursor.classList.add('is-clicking')
        await wait(220)
        if (cancelled) {
          return
        }
        cursor.classList.remove('is-clicking')
        prGen.classList.add('is-scanning')
        // Why: the PR phase does not re-pulse the SC file rows — the commit
        // phase already showed the read→write tie to the diff. Reusing the
        // pulse here would double-signal and read as confused state.
        await wait(420)
        if (cancelled) {
          return
        }

        if (prTitlePh) {
          prTitlePh.style.display = 'none'
        }
        for (const ch of PR_TITLE) {
          if (cancelled) {
            return
          }
          prTitleTyped.textContent = (prTitleTyped.textContent ?? '') + ch
          await wait(20)
        }
        if (prBodyPh) {
          prBodyPh.style.display = 'none'
        }
        for (const ch of PR_BODY) {
          if (cancelled) {
            return
          }
          prBodyTyped.textContent = (prBodyTyped.textContent ?? '') + ch
          await wait(ch === '\n' ? 60 : 10)
        }
        prGen.classList.remove('is-scanning')
        // Why: same green flash as Commit, on the Create PR button once both
        // fields are filled — keeps the two beats visually parallel.
        prCreate.classList.add('is-ready')
        await wait(540)
        if (cancelled) {
          return
        }
        prCreate.classList.remove('is-ready')

        await wait(2200)
        if (cancelled) {
          return
        }
      }
    }

    void loop()

    return () => {
      cancelled = true
      timers.forEach((t) => window.clearTimeout(t))
    }
  }, [reducedMotion])

  return (
    <div ref={rootRef} className="ravs-ship-root" data-page="ship">
      <div className="ravs-ship-stack">
        <div className="ravs-sc-card">
          <div className="ravs-sc-header">
            <span className="ravs-sc-ahead">
              <ArrowUpIcon />{' '}
              {translate(
                'auto.components.feature.wall.ReviewShipAnimatedVisual.cd8a3a39d7',
                '3 commits ahead'
              )}
            </span>
          </div>
          <div className="ravs-sc-commit-area">
            <div className="ravs-sc-textarea" data-commit-textarea>
              <button
                type="button"
                className="ravs-sc-sparkle"
                data-commit-sparkle
                aria-label={translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.d1a7f15876',
                  'Generate commit message with AI'
                )}
              >
                <Sparkles className="size-3.5" />
              </button>
              <span className="ravs-placeholder" data-commit-placeholder>
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.7347fa5839',
                  'Message'
                )}
              </span>
              <span data-commit-typed />
              <span className="ravs-caret" />
            </div>
            <div className="ravs-sc-split" data-sc-split>
              <span className="ravs-primary">
                <CheckTinyIcon />{' '}
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.a079083a6c',
                  'Commit'
                )}
              </span>
              <span className="ravs-chev">
                <ChevDownIcon />
              </span>
            </div>
          </div>
          <div className="ravs-sc-changes-header">
            <span>
              {translate(
                'auto.components.feature.wall.ReviewShipAnimatedVisual.e725000cd7',
                'Changes'
              )}{' '}
              <span className="ravs-sc-changes-count">{SHIP_FILES.length}</span>
            </span>
            <span className="ravs-sc-view-all">
              {translate(
                'auto.components.feature.wall.ReviewShipAnimatedVisual.ea0100dd15',
                'View all'
              )}
            </span>
          </div>
          <div className="ravs-sc-files">
            {SHIP_FILES.map((name) => (
              <div className="ravs-sc-file" data-sc-file key={name}>
                <span className="ravs-sc-ficon">
                  <FileIcon />
                </span>
                <span className="ravs-sc-fname">{name}</span>
                <span className="ravs-sc-fmark">M</span>
              </div>
            ))}
          </div>
        </div>

        <div className="ravs-pr-dialog">
          <div className="ravs-pr-head">
            <div className="ravs-pr-title-text">
              {translate(
                'auto.components.feature.wall.ReviewShipAnimatedVisual.c30cd930ff',
                'Create Pull Request'
              )}
            </div>
            <button
              type="button"
              className="ravs-pr-gen-btn"
              data-pr-gen-btn
              aria-label={translate(
                'auto.components.feature.wall.ReviewShipAnimatedVisual.e4473d438f',
                'Generate with AI'
              )}
              title={translate(
                'auto.components.feature.wall.ReviewShipAnimatedVisual.e4473d438f',
                'Generate with AI'
              )}
            >
              <Sparkles className="size-3.5" />
            </button>
          </div>
          <div className="ravs-pr-body">
            <div className="ravs-pr-field">
              <div className="ravs-pr-field-label">
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.ce7d5d3a18',
                  'Base branch'
                )}
              </div>
              <span className="ravs-pr-base">
                <GitBranch className="size-3" />{' '}
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.3b9b96d6a6',
                  'main'
                )}
              </span>
            </div>
            <div className="ravs-pr-field">
              <div className="ravs-pr-field-label">
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.54a093c52d',
                  'Title'
                )}
              </div>
              <div className="ravs-pr-input" data-pr-title>
                <span className="ravs-placeholder">
                  {translate(
                    'auto.components.feature.wall.ReviewShipAnimatedVisual.07da9245cc',
                    'Pull request title'
                  )}
                </span>
                <span data-pr-title-typed />
              </div>
            </div>
            <div className="ravs-pr-field">
              <div className="ravs-pr-field-label">
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.3774b80eae',
                  'Description'
                )}
              </div>
              <div className="ravs-pr-input is-body" data-pr-body>
                <span className="ravs-placeholder">
                  {translate(
                    'auto.components.feature.wall.ReviewShipAnimatedVisual.bcd5cae3c4',
                    'Pull request description'
                  )}
                </span>
                <span data-pr-body-typed />
              </div>
            </div>
            <div className="ravs-pr-footer">
              <button type="button" className="ravs-pr-btn is-outline">
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.62544e0852',
                  'Cancel'
                )}
              </button>
              <button type="button" className="ravs-pr-btn is-solid" data-pr-create-btn>
                {translate(
                  'auto.components.feature.wall.ReviewShipAnimatedVisual.4d99496b8c',
                  'Create PR'
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
      <div className="ravs-cursor" data-cursor>
        <CursorIcon />
        <span className="ravs-ripple" />
      </div>
      <ReviewShipVisualStyles />
    </div>
  )
}
