export const RUNTIME_FILE_WATCH_CRAWL_TIMEOUT_MS = 60_000
export const RUNTIME_FILE_WATCH_CANCEL_TIMEOUT_MS = 60_000
export const RUNTIME_FILE_WATCH_EXIT_DEADLINE_MS = 10_000
export const RUNTIME_FILE_WATCH_MAX_SETUP_ATTEMPTS = 2
