export const LINEAR_ISSUE_FLAGS = new Set([
  'help',
  'json',
  'pairing-code',
  'environment',
  'current',
  'comments',
  'children',
  'depth',
  'attachments',
  'relations',
  'activity',
  'full',
  'workspace',
  'id'
])
export const LINEAR_SEARCH_FLAGS = new Set([
  'help',
  'json',
  'pairing-code',
  'environment',
  'limit',
  'workspace',
  'query'
])
export const LINEAR_TEAM_LIST_FLAGS = new Set([
  'help',
  'json',
  'pairing-code',
  'environment',
  'workspace'
])
export const LINEAR_TEAM_LOOKUP_FLAGS = new Set([
  'help',
  'json',
  'pairing-code',
  'environment',
  'team',
  'workspace'
])
export const LINEAR_PROJECT_LIST_FLAGS = new Set([
  'help',
  'json',
  'pairing-code',
  'environment',
  'query',
  'limit',
  'workspace'
])
export const LINEAR_LIST_FLAGS = new Set([
  'help',
  'json',
  'pairing-code',
  'environment',
  'filter',
  'team',
  'limit',
  'workspace'
])
export const LINEAR_MCP_ISSUE_LIST_FLAGS = new Set([
  'help',
  'json',
  'pairing-code',
  'environment',
  'team',
  'cycle',
  'label',
  'limit',
  'query',
  'state',
  'cursor',
  'order-by',
  'project',
  'release',
  'assignee',
  'delegate',
  'parent-id',
  'priority',
  'created-at',
  'updated-at',
  'include-archived',
  'workspace'
])
